import{a as S,S as q,i as c}from"./assets/vendor-550cebad.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))i(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&i(a)}).observe(document,{childList:!0,subtree:!0});function s(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(t){if(t.ep)return;t.ep=!0;const o=s(t);fetch(t.href,o)}})();async function g(e,r,s){const i="https://pixabay.com/api/",t={key:"42941472-1aaa1e5ed1787820ede60bd86",q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:r,per_page:s};return(await S.get(i,{params:t})).data}const l=document.querySelector(".gallery"),y=new q(".gallery a",{captionsData:"alt",captionDelay:250});y.refresh();function L(e){const r=e.map(({largeImageURL:s,webformatURL:i,tags:t,likes:o,views:a,comments:M,downloads:v})=>`
      <li class="card">
        <a href="${s}" class="link">
          <img src="${i}" alt="${t}">
          <ul class="list-container">
          <li class="item-description"><h3>Likes</h3> <p>${o}</p></li>
          <li class="item-description"><h3>Views</h3> <p>${a}</p></li>
          <li class="item-description"><h3>Comments</h3> <p>${M}</p></li>
          <li class="item-description"><h3>Downloads</h3> <p>${v}</p></li>
        </ul>
        </a>
      </li>
    `).join("");l.insertAdjacentHTML("beforeend",r),y.refresh()}function b(){const e=document.createElement("p");e.classList.add("result-message"),e.textContent="We're sorry, but you've reached the end of search results.",l.insertAdjacentElement("afterend",e)}const C=document.querySelector(".form"),p=document.querySelector(".search-input"),E=document.querySelector(".loader"),m=document.querySelector(".load-more-btn");h();let n=1,d="";const f=15;C.addEventListener("submit",H);async function H(e){if(e.preventDefault(),l.innerHTML="",d=p.value.trim(),n=1,d===""){c.error({title:"Error",message:"Please fill in the field for search!",position:"topCenter"}),u();return}$(),w();try{const r=await g(d,n,f),s=r.totalHits;if(r.hits.length===0){l.innerHTML="",c.info({title:"Info",message:"Sorry, there are no images matching your search query. Please try again!",position:"topCenter"}),u();return}else L(r.hits),p.value="",P();f*n>=s&&(u(),b())}catch(r){console.error("Error fetching images:",r),c.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again.",position:"topCenter"})}finally{h()}}m.addEventListener("click",async()=>{try{m&&(n+=1);const e=await g(d,n,f),r=e.totalHits;L(e.hits),w(),f*n>=r&&(u(),b());const s=l.firstElementChild.getBoundingClientRect().height;window.scrollBy({top:s*2,behavior:"smooth"})}catch(e){console.error("Error fetching more images:",e),c.error({title:"Error",message:`Error fetching more images: ${e}`})}finally{h()}});function w(){E.classList.remove("hidden")}function h(){E.classList.add("hidden")}function P(){m.style.display="block"}function u(){m.style.display="none"}function $(){const e=document.querySelector(".result-message");e&&e.remove()}
//# sourceMappingURL=commonHelpers.js.map
